### ISSUE TITLE
Iterator in fizzbuzz.py

### ISSUE THREAD

**Issue by ultra-programmer** [ultra-programmer/FizzBuzz#1]
# Do I need to import the Iterator module?
I tested to see if the program worked without the module, and it seemed to work in the same way. Is there some benefitI'm not seeing? Or is it just an extra thing I should be able to delete?

**Comment by uzerjamal** [comment]
You don't need iterator. It's better to remove it

**Comment by ultra-programmer** [comment]
@uzerjamal But why would I not need it?
